### ISSUE TITLE
Feature request: reload command

### ISSUE THREAD

**Issue by SlimeDog** [PaulAnthonyReitz/ReitzMMO#11]
Please implement **reitz reload**. It should be executable with **reitzmmo.reload** permission, from in-game and at the console. It will make configuration testing possible.

**Comment by RitzDaCat** [comment]
799b7709377702a326ad32e3174ad74f84cb01d9

**Comment by RitzDaCat** [comment]
Was just pushed in 1.16, let me know if you have any issues.

**Comment by SlimeDog** [comment]
I do not find the 1.16 download.

**Comment by SlimeDog** [comment]
Spigot 1.14.2
ReitzMMO 1.16

at the console:
```
>reitz reload
[22:28:59] [Server thread/WARN]: Unexpected exception while parsing console command "reitz reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'reitz' in plugin ReitzMMO v1.16
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NullPointerException
        at com.paully104.reitzmmo.Command_Handlers.ReitzRPGMain.onCommand(ReitzRPGMain.java:29) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-1.14.2.jar-2019-06-07-2036:git-Spigot-baafee9-7cc7719]
        ... 8 more
```
same with
```
> reitz help
```
or just
```
> reitz
```
