### ISSUE TITLE
Error when starting the server. 

### ISSUE THREAD

**Issue by avalon666** [PaulAnthonyReitz/ReitzMMO#12]
`[11:56:55] [Server thread/INFO]: [ReitzMMO] Enabling ReitzMMO v1.15
[11:56:55] [Server thread/INFO]: [ReitzMMO] ReitzRPGMMO is now enabled
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Arrows.setCustomArrow(Custom_Arrows.java:24)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:95)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setCustomWoodBow(Custom_Bows.java:33)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:96)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setStoneBow(Custom_Bows.java:46)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:97)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setIronBow(Custom_Bows.java:60)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:98)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setGoldBow(Custom_Bows.java:74)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:99)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setDiamondBow(Custom_Bows.java:89)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:100)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[11:56:55] [Server thread/WARN]: java.lang.Throwable: Warning: A plugin is creating a recipe using a Deprecated method. This will cause you to receive warnings stating 'Tried to load unrecognized recipe: bukkit:<ID>'. Please ask the author to give their recipe a static key using NamespacedKey.
[11:56:55] [Server thread/WARN]: 	at org.bukkit.inventory.ShapelessRecipe.<init>(ShapelessRecipe.java:29)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Custom_Recipes.Custom_Bows.setLlamaBow(Custom_Bows.java:104)
[11:56:55] [Server thread/WARN]: 	at com.paully104.reitzmmo.Main.onEnable(Main.java:101)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280)
[11:56:55] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:855)
[11:56:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)`

No extended bows can be produced. Manufacturing recipe?

**Comment by RitzDaCat** [comment]
a3955213c1cacabfb233297481f4133aa602bae3

**Comment by RitzDaCat** [comment]
54f5417ee9352cf59152cf871792a7f06014f29a
